name: Demo

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      VERSION: 0
    outputs:
      version: ${{ steps.versioning.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'      
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: echo "npm test"
      - name: Get Version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> "$GITHUB_ENV"
      - name: Print Version
        run: echo "${{ env.VERSION }}"
      - id: versioning
        name: Save Version
        run: echo "version=${{ env.VERSION }}" >> "$GITHUB_OUTPUT"

  delivery:
    runs-on: ubuntu-22.04
    needs: build
    env:
      IMAGE_TAG: ${{ needs.build.outputs.version }}
    steps:
      - name: Print Version
        run: echo "${{ env.IMAGE_TAG }}"
      - name: Docker Build
        run: echo "docker build"
      - name: Docker Push
        run: echo "docker push"
